theme: jekyll-theme-minimal

title: "MulleSDE"
description: "The IDE for the command line. Written in bash."

highlighter: rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

